import SwiftUI
import Cocoa
import InputMethodKit

class AppDelegate: NSObject, NSApplicationDelegate {
    var statusItem: NSStatusItem?
    var eventTap: CFMachPort?
    var runLoopSource: CFRunLoopSource?
    
    // Rust Engine Bridge
    let engine = VietimeEngineBridge()
    var isVietnamese = true
    
    func applicationDidFinishLaunching(_ notification: Notification) {
        // Run in background (accessory policy hides dock icon)
        NSApp.setActivationPolicy(.accessory)
        
        setupStatusMenu()
        setupEventTap()
    }
    
    func setupStatusMenu() {
        statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.variableLength)
        updateStatusIcon()
        
        let menu = NSMenu()
        
        let titleItem = NSMenuItem(title: "Bộ gõ Vietime (Rust Core)", action: nil, keyEquivalent: "")
        titleItem.isEnabled = false
        menu.addItem(titleItem)
        menu.addItem(NSMenuItem.separator())
        
        let toggleItem = NSMenuItem(title: "Chế độ: Tiếng Việt", action: #selector(toggleLanguage), keyEquivalent: " ")
        toggleItem.keyEquivalentModifierMask = [.control] // Control + Space global hotkey
        menu.addItem(toggleItem)
        
        menu.addItem(NSMenuItem.separator())
        
        let resetItem = NSMenuItem(title: "Reset bộ nhớ bộ gõ", action: #selector(resetEngine), keyEquivalent: "")
        menu.addItem(resetItem)
        
        menu.addItem(NSMenuItem.separator())
        
        let quitItem = NSMenuItem(title: "Thoát bộ gõ", action: #selector(quitApp), keyEquivalent: "q")
        menu.addItem(quitItem)
        
        statusItem?.menu = menu
    }
    
    @objc func toggleLanguage() {
        isVietnamese.toggle()
        updateStatusIcon()
        engine.reset()
    }
    
    @objc func resetEngine() {
        engine.reset()
    }
    
    @objc func quitApp() {
        NSApp.terminate(nil)
    }
    
    func updateStatusIcon() {
        if let button = statusItem?.button {
            button.title = isVietnamese ? "🇻🇳 V" : "🇺🇸 E"
            button.font = NSFont.systemFont(ofSize: 13, weight: .semibold)
        }
        if let menu = statusItem?.menu {
            if menu.items.count > 2 {
                menu.items[2].title = isVietnamese ? "Chế độ: Tiếng Việt" : "Chế độ: Tiếng Anh"
            }
        }
    }
    
    func setupEventTap() {
        let eventMask = (1 << CGEventType.keyDown.rawValue) |
                        (1 << CGEventType.keyUp.rawValue) |
                        (1 << CGEventType.flagsChanged.rawValue) |
                        (1 << CGEventType.leftMouseDown.rawValue) |
                        (1 << CGEventType.rightMouseDown.rawValue)
        
        let selfRef = Unmanaged.passUnretained(self).toOpaque()
        
        eventTap = CGEvent.tapCreate(
            tap: .cgSessionEventTap,
            place: .headInsertEventTap,
            options: .defaultTap,
            eventsOfInterest: CGEventMask(eventMask),
            callback: { (proxy, type, event, refcon) -> Unmanaged<CGEvent>? in
                guard let refcon = refcon else { return Unmanaged.passUnretained(event) }
                let mySelf = Unmanaged<AppDelegate>.fromOpaque(refcon).takeUnretainedValue()
                return mySelf.handleEvent(proxy: proxy, type: type, event: event)
            },
            userInfo: selfRef
        )
        
        if let tap = eventTap {
            runLoopSource = CFMachPortCreateRunLoopSource(kCFAllocatorDefault, tap, 0)
            CFRunLoopAddSource(CFRunLoopGetCurrent(), runLoopSource, .commonModes)
            CGEvent.tapEnable(tap: tap, enable: true)
            print("Event tap successfully installed.")
        } else {
            print("Failed to create event tap. Make sure Accessibility permissions are enabled.")
            showAccessibilityAlert()
        }
    }
    
    func handleEvent(proxy: CGEventTapProxy, type: CGEventType, event: CGEvent) -> Unmanaged<CGEvent>? {
        if type == .leftMouseDown || type == .rightMouseDown {
            engine.reset()
            return Unmanaged.passUnretained(event)
        }
        
        // 1. Skip events generated by our own app to avoid infinite typing loops
        if event.getIntegerValueField(.eventSourceUserData) == 42 {
            return Unmanaged.passUnretained(event)
        }
        
        let flags = event.flags
        let keyCode = event.getIntegerValueField(.keyboardEventKeycode)
        
        // 2. Global switch hotkey: Control + Space
        if type == .keyDown {
            let isControl = flags.contains(.maskControl)
            if keyCode == 49 && isControl {
                toggleLanguage()
                return nil // Swallow event
            }
        }
        
        // 3. Skip if English mode is active
        if !isVietnamese {
            return Unmanaged.passUnretained(event)
        }
        
        // 4. Feed events to Rust Core Engine
        if type == .keyDown {
            let isShift = flags.contains(.maskShift)
            let isAlphaShift = flags.contains(.maskAlphaShift)
            let capsStatus: UInt8 = isShift ? 1 : (isAlphaShift ? 2 : 0)
            
            // Check modifier keys (Cmd, Option, Ctrl)
            let otherControlKey = flags.contains(.maskCommand) || flags.contains(.maskAlternate) || flags.contains(.maskControl)
            
            if let result = engine.handleKey(
                event: .keyboard,
                state: .keyDown,
                data: UInt16(keyCode),
                capsStatus: capsStatus,
                otherControlKey: otherControlKey
            ) {
                if result.code == .doNothing {
                    return Unmanaged.passUnretained(event)
                } else if result.code == .willProcess || result.code == .restore || result.code == .restoreAndStartNewSession {
                    // Send backspaces
                    if result.backspaceCount > 0 {
                        for _ in 0..<result.backspaceCount {
                            sendBackspace(proxy: proxy)
                        }
                    }
                    
                    // Send characters
                    if !result.characters.isEmpty {
                        let newStr = String(result.characters)
                        sendUnicodeString(newStr, proxy: proxy)
                    }
                    
                    if result.code == .restoreAndStartNewSession {
                        engine.reset()
                    }
                    
                    return nil // Consume original keypress
                }
            }
        }
        
        return Unmanaged.passUnretained(event)
    }
    
    private func sendBackspace(proxy: CGEventTapProxy) {
        let source = CGEventSource(stateID: .privateState)
        
        let eventDown = CGEvent(keyboardEventSource: source, virtualKey: 51, keyDown: true)
        let eventUp = CGEvent(keyboardEventSource: source, virtualKey: 51, keyDown: false)
        
        eventDown?.setIntegerValueField(.eventSourceUserData, value: 42)
        eventUp?.setIntegerValueField(.eventSourceUserData, value: 42)
        
        eventDown?.tapPostEvent(proxy)
        eventUp?.tapPostEvent(proxy)
    }
    
    private func sendUnicodeString(_ string: String, proxy: CGEventTapProxy) {
        let source = CGEventSource(stateID: .privateState)
        let utf16Chars = Array(string.utf16)
        
        let eventDown = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: true)
        let eventUp = CGEvent(keyboardEventSource: source, virtualKey: 0, keyDown: false)
        
        eventDown?.keyboardSetUnicodeString(stringLength: utf16Chars.count, unicodeString: utf16Chars)
        eventUp?.keyboardSetUnicodeString(stringLength: utf16Chars.count, unicodeString: utf16Chars)
        
        eventDown?.setIntegerValueField(.eventSourceUserData, value: 42)
        eventUp?.setIntegerValueField(.eventSourceUserData, value: 42)
        
        eventDown?.tapPostEvent(proxy)
        eventUp?.tapPostEvent(proxy)
    }
    
    func showAccessibilityAlert() {
        let alert = NSAlert()
        alert.messageText = "Yêu cầu quyền trợ năng (Accessibility)"
        alert.informativeText = "Để gõ tiếng Việt toàn hệ thống, vui lòng mở:\nSystem Settings -> Privacy & Security -> Accessibility\nvà tích chọn cho phép ứng dụng này."
        alert.alertStyle = .warning
        alert.addButton(withTitle: "Mở Cài đặt Trợ năng")
        alert.addButton(withTitle: "Bỏ qua")
        
        let res = alert.runModal()
        if res == .alertFirstButtonReturn {
            if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility") {
                NSWorkspace.shared.open(url)
            }
        }
    }
}

@main
struct VietimeApp: App {
    @NSApplicationDelegateAdaptor(AppDelegate.self) var appDelegate
    
    var body: some Scene {
        Settings {
            VStack(spacing: 20) {
                Text("Bộ Gõ Tiếng Việt Vietime")
                    .font(.title)
                    .fontWeight(.bold)
                Text("Đang chạy ẩn trong thanh Menu Bar.")
                    .foregroundColor(.secondary)
                Button("Kiểm tra quyền Trợ năng (Accessibility)") {
                    let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true]
                    AXIsProcessTrustedWithOptions(options as CFDictionary)
                }
                .buttonStyle(.borderedProminent)
            }
            .frame(width: 350, height: 180)
            .padding()
        }
    }
}
