name: Rust Windows Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build binaries
      run: cargo build --release -p platform-win -p ui-settings

    - name: Upload a Build Artifact
      id: upload
      uses: actions/upload-artifact@v4
      with:
        name: XXKey-Windows-Binaries
        path: |
          target/release/xxkey-daemon.exe
          target/release/xxkey-settings.exe
